# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr:
 branches:
   include:
     - '*'

pool:
  vmImage: 'windows-latest'

steps:

- script: dir /s

- task: DotNetCoreCLI@2
  displayName: "BuildBot"
  inputs:
    command: 'build'
    projects: 'StackoverflowChatbot/StackoverflowChatbot.csproj'

- task: ArchiveFiles@2
  displayName: Zip up results
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: AzureFileCopy@4
  displayName: Copy To Azure
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    azureSubscription: 'Base Subscription(1)(fa77dc99-d303-482a-a595-14414e3cb5e5)'
    Destination: 'AzureBlob'
    storage: 'leerbcsharpbot'
    ContainerName: 'deploy'