// <auto-generated />
using System;
using Botler.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Botler.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20220623194231_AddMessageChannelIds")]
    partial class AddMessageChannelIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("StackoverflowChatbot.Database.Dbos.MessageDbo", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPlatform")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageAdditionalDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginPlatform")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("DestinationMessageId", "DestinationPlatform");

                    b.HasIndex("OriginMessageId", "OriginPlatform");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
